# This file was generated by go2nix.
{ stdenv, buildGoPackage, fetchgit, fetchhg, fetchbzr, fetchsvn, makeWrapper }:

buildGoPackage rec {
  name = "wingo-${version}";
  version = "20160709-${stdenv.lib.strings.substring 0 7 rev}";
  rev = "32ab09196204472baa36bcf469909ac97721b53f";

  goPackagePath = "github.com/BurntSushi/wingo";

  src = fetchgit {
    inherit rev;
    url = "https://github.com/BurntSushi/wingo";
    sha256 = "0gx6py43f6q9j1l2f102xfsdjrfg0awwykrh9fqqji74v7r526jk";
  };

  ## without this a cycle happens between $out and $bin in postInstall wrapProgram
  outputs = [ "out" ];

  preInstall = ''
    export bin=$out
  '';
  ## -- 

  buildInputs = [ makeWrapper ];

  postInstall = ''
      wrapProgram $bin/bin/wingo \
        --set GOPATH "$out/share/go/"
              
      wrapProgram $bin/bin/wingo-cmd \
        --set GOPATH "$out/share/go/"
  '';

  goDeps = ./deps.nix;

  # TODO: add metadata https://nixos.org/nixpkgs/manual/#sec-standard-meta-attributes
  meta = {
  };
}
