# This file was generated by go2nix.
[
  {
    goPackagePath = "github.com/BurntSushi/cmd";
    fetch = {
      type = "git";
      url = "https://github.com/BurntSushi/cmd";
      rev = "d54777ad4400afdb40a9d138416f6d27d746a769";
      sha256 = "0a2fa03favyh01g88mmqb25fkz431bczhfjb420h3pc1x6piz4cm";
    };
  }
  {
    goPackagePath = "github.com/BurntSushi/freetype-go";
    fetch = {
      type = "git";
      url = "https://github.com/BurntSushi/freetype-go";
      rev = "b763ddbfe298bf71c999a2833470da508f3a0677";
      sha256 = "127gav0s2rwdr8ndkhyz9yxlg6jkmfyqyhxb39wl658rwc78nwlf";
    };
  }
  {
    goPackagePath = "github.com/BurntSushi/graphics-go";
    fetch = {
      type = "git";
      url = "https://github.com/BurntSushi/graphics-go";
      rev = "b43f31a4a96688fba0b612e25e22648b9267e498";
      sha256 = "1084wkrj5l6j48s9lkh28h2zgmw8kp63ra1yw1nfpkf0f6hil3hn";
    };
  }
  {
    goPackagePath = "github.com/BurntSushi/gribble";
    fetch = {
      type = "git";
      url = "https://github.com/BurntSushi/gribble";
      rev = "956d80ded3b2206b1e566a16d08dfda1f0995e54";
      sha256 = "0wz1mr0bgr241kzv47c5f5jywk1n20pkcr60shm0fc19ipabszrh";
    };
  }
  {
    goPackagePath = "github.com/BurntSushi/xdg";
    fetch = {
      type = "git";
      url = "https://github.com/BurntSushi/xdg";
      rev = "e80d3446fea190e21fbd294569844f066e47ccfc";
      sha256 = "10s209vr7hg7lanw2zxa22cayc651l1gpxwylkhwiblmn354x6ga";
    };
  }
  {
    goPackagePath = "github.com/BurntSushi/xgb";
    fetch = {
      type = "git";
      url = "https://github.com/BurntSushi/xgb";
      rev = "27f122750802c950b2c869a5b63dafcf590ced95";
      sha256 = "18lp2x8f5bljvlz0r7xn744f0c9rywjsb9ifiszqqdcpwhsa0kvj";
    };
  }
  {
    goPackagePath = "github.com/BurntSushi/xgbutil";
    fetch = {
      type = "git";
      url = "https://github.com/BurntSushi/xgbutil";
      rev = "f7c97cef3b4e6c88280a5a7091c3314e815ca243";
      sha256 = "0kw0zmpbnymnalpj2wsvxbb7p5c297kv0qhyj20mcwg8dz64drnp";
    };
  }
  {
    goPackagePath = "github.com/str1ngs/ansi";
    fetch = {
      type = "git";
      url = "https://github.com/str1ngs/ansi";
      rev = "5dc1bc5ac1f5bcbf5bd4818dd27ef912beb4bb7c";
      sha256 = "1r9zddany6z6y2ng8vp2f0zswfxmkkd4ma97dkpgkivmgnqalf7f";
    };
  }
]
